{
    "name": "impress_production_billing",
    "version": "0.1.2",
    "summary": """ Module to allow billing of MOs directly through SOs """,
    "author": "Cédric Paradis",
    "website": "",
    "category": "Sales",
    "depends": ["base", "web", "mrp", "purchase", "sale_management", "portal"],
    "data": [
        "security/impress_production_billing_security.xml",
        "security/ir.model.access.csv",
        "views/mrp_production_views.xml",
        "views/portal/portal_mrp_production_views.xml",
        "views/portal/portal_production.xml",
        "views/portal/portal_sale_order_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "impress_production_billing/static/src/scss/manufacturing_portal.scss",
        ],
        "impress_production_billing.webclient": [
            ("include", "web._assets_helpers"),
            ("include", "web._assets_backend_helpers"),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/src/libs/fontawesome/css/font-awesome.css",
            "web/static/lib/odoo_ui_icons/*",
            "web/static/lib/select2/select2.css",
            "web/static/lib/select2-bootstrap-css/select2-bootstrap.css",
            "web/static/src/webclient/navbar/navbar.scss",
            "web/static/src/scss/animation.scss",
            "web/static/src/core/colorpicker/colorpicker.scss",
            "web/static/src/scss/mimetypes.scss",
            "web/static/src/scss/ui.scss",
            "web/static/src/legacy/scss/ui.scss",
            "web/static/src/views/fields/translation_dialog.scss",
            "web/static/src/scss/fontawesome_overridden.scss",
            "web/static/src/module_loader.js",
            "web/static/src/session.js",
            "web/static/lib/luxon/luxon.js",
            "web/static/lib/owl/owl.js",
            "web/static/lib/owl/odoo_module.js",
            "web/static/lib/jquery/jquery.js",
            "web/static/lib/popper/popper.js",
            "web/static/lib/bootstrap/js/dist/dom/data.js",
            "web/static/lib/bootstrap/js/dist/dom/event-handler.js",
            "web/static/lib/bootstrap/js/dist/dom/manipulator.js",
            "web/static/lib/bootstrap/js/dist/dom/selector-engine.js",
            "web/static/lib/bootstrap/js/dist/base-component.js",
            "web/static/lib/bootstrap/js/dist/alert.js",
            "web/static/lib/bootstrap/js/dist/button.js",
            "web/static/lib/bootstrap/js/dist/carousel.js",
            "web/static/lib/bootstrap/js/dist/collapse.js",
            "web/static/lib/bootstrap/js/dist/dropdown.js",
            "web/static/lib/bootstrap/js/dist/modal.js",
            "web/static/lib/bootstrap/js/dist/offcanvas.js",
            "web/static/lib/bootstrap/js/dist/tooltip.js",
            "web/static/lib/bootstrap/js/dist/popover.js",
            "web/static/lib/bootstrap/js/dist/scrollspy.js",
            "web/static/lib/bootstrap/js/dist/tab.js",
            "web/static/lib/bootstrap/js/dist/toast.js",
            "web/static/lib/select2/select2.js",
            "web/static/src/legacy/js/libs/bootstrap.js",
            "web/static/src/legacy/js/libs/jquery.js",
            ("include", "web._assets_bootstrap"),
            "base/static/src/css/modules.css",
            "web/static/src/core/utils/transitions.scss",
            "web/static/src/core/**/*",
            ("remove", "web/static/src/core/emoji_picker/emoji_data.js"),
            "web/static/src/search/**/*",
            "web/static/src/views/*.js",
            "web/static/src/views/*.xml",
            "web/static/src/views/*.scss",
            "web/static/src/views/fields/**/*",
            "web/static/src/views/form/**/*",
            "web/static/src/views/kanban/**/*",
            "web/static/src/views/list/**/*",
            "web/static/src/model/**/*",
            "web/static/src/views/view_button/**/*",
            "web/static/src/views/view_components/**/*",
            "web/static/src/views/view_dialogs/**/*",
            "web/static/src/views/widgets/**/*",
            "web/static/src/webclient/**/*",
            ("remove", "web/static/src/webclient/clickbot/clickbot.js"),  # lazy loaded
            ("remove", "web/static/src/views/form/button_box/*.scss"),
            # remove the report code and whitelist only what's needed
            ("remove", "web/static/src/webclient/actions/reports/**/*"),
            "web/static/src/webclient/actions/reports/*.js",
            "web/static/src/webclient/actions/reports/*.xml",
            "web/static/src/env.js",
            "web/static/src/legacy/scss/fields.scss",
            "base/static/src/scss/res_partner.scss",
            # Form style should be computed before
            "web/static/src/views/form/button_box/*.scss",
            "impress_production_billing/static/src/manufacturing_portal/*",
            "web/static/src/start.js",
        ],
    },
    "installable": True,
    "license": "GPL-2",
}
